class AppStrings {
  static String get(String key, {String locale = 'da'}) {
    return (_strings[locale] ?? _strings['da']!)[key] ?? key;
  }

  static const Map<String, Map<String, String>> _strings = {
    'da': {
      'appTitle': 'Løbecoachen',
      'welcome_title': 'Din personlige\nløbecoach',
      'welcome_subtitle': 'Tilpasset kontormennesket der vil løbe',
      'welcome_cta': 'Kom i gang',
      'language_title': 'Vælg sprog',
      'language_da': 'Dansk',
      'language_en': 'English',
      'level_title': 'Hvad er dit niveau?',
      'level_beginner': 'Nybegynder',
      'level_beginner_desc': 'Lige startet eller tilbage efter en pause',
      'level_intermediate': 'Øvet',
      'level_intermediate_desc': 'Løber regelmæssigt, vil forbedre mig',
      'level_experienced': 'Erfaren',
      'level_experienced_desc': 'Løber 3+ gange om ugen med mål',
      'environment_title': 'Hvor løber du?',
      'environment_subtitle': 'Du kan altid ændre dette senere',
      'env_treadmill': 'Løbebånd',
      'env_treadmill_desc': 'Indendørs, kontrolleret tempo',
      'env_trail': 'Trailløb',
      'env_trail_desc': 'Skov, bakker og ubanet terræn',
      'env_road': 'Vej og løbespor',
      'env_road_desc': 'Asfalt, park og løberuder',
      'goal_title': 'Hvad er dit mål?',
      'goal_subtitle': 'Vi tilpasser dine træningsprogrammer',
      'goal_fitness': 'Generel motion',
      'goal_fitness_sub': 'Holde mig i form',
      'goal_5k': '5 kilometer',
      'goal_5k_sub': 'Gennemføre eller forbedre din 5K',
      'goal_10k': '10 kilometer',
      'goal_10k_sub': 'Gennemføre eller forbedre din 10K',
      'goal_half': 'Halvmarathon',
      'goal_half_sub': '21,1 km – en rigtig udfordring',
      'goal_marathon': 'Marathon',
      'goal_marathon_sub': '42,2 km – det ultimative mål',
      'nav_home': 'Hjem',
      'nav_training': 'Træning',
      'nav_coach': 'Coach',
      'nav_progress': 'Fremskridt',
      'nav_settings': 'Indst.',
      'home_greeting_morning': 'God morgen!',
      'home_greeting_afternoon': 'God eftermiddag!',
      'home_greeting_evening': 'God aften!',
      'home_recommendation': 'Dagens anbefaling',
      'home_streak': 'dages streak',
      'home_sessions': 'løbeture',
      'home_quick_start': 'Start løbetur',
      'home_no_streak': 'Start din streak i dag',
      'home_tip_title': 'Coach-tip',
      'training_title': 'Vælg træningsmodel',
      'training_subtitle': 'Tre måder at tælle din løbetur på',
      'model_minutes': 'Minutter',
      'model_minutes_desc': 'Intervalløb talt i minutter. Simpelt og effektivt.',
      'model_bpm': 'BPM',
      'model_bpm_desc': 'Find musikken der matcher dit mål-tempo.',
      'model_lamppost': 'Lygtepæle',
      'model_lamppost_desc': 'Brug gadernes lygtepæle som naturlige interval-markører.',
      'model_premium': 'Premium',
      'bpm_title': 'Din BPM-anbefaling',
      'bpm_explanation': 'For at nå dit mål anbefaler vi at løbe til musik ved:',
      'bpm_songs_title': 'Sange ved denne BPM',
      'bpm_tip': 'Søg sangene på Spotify eller Apple Music og løb til rytmen.',
      'bpm_start': 'Start løbeturen',
      'bpm_what_is': 'Hvad er BPM?',
      'bpm_what_is_answer': 'BPM (Beats Per Minute) er musikens tempo. Når du løber til musik med en BPM der matcher din skredefrekvens, løber du mere rytmisk og effektivt.',
      'minutes_title': 'Interval-timer',
      'minutes_round': 'Runde',
      'minutes_of': 'af',
      'minutes_run': 'LØB',
      'minutes_rest': 'HVIL',
      'minutes_start': 'Start',
      'minutes_pause': 'Pause',
      'minutes_resume': 'Fortsæt',
      'minutes_stop': 'Stop',
      'minutes_complete': 'Træning gennemført!',
      'minutes_plan': 'Træningsplan',
      'lamppost_title': 'Lygtepæl-interval',
      'lamppost_run': 'LØB til næste lygtepæl',
      'lamppost_rest': 'HVIL – gå til næste lygtepæl',
      'lamppost_tap': 'TAP ved lygtepælen',
      'lamppost_complete': 'Runde gennemført!',
      'lamppost_total': 'Lygtepæle passeret',
      'lamppost_rounds': 'Runder',
      'lamppost_stop': 'Afslut træning',
      'coach_title': 'Din coach',
      'coach_greeting': 'Hej! Jeg er din løbecoach. Stil mig et spørgsmål om løbetræning.',
      'coach_placeholder': 'Skriv et spørgsmål...',
      'coach_send': 'Send',
      'coach_suggestion_breathing': 'Vejrtrækning',
      'coach_suggestion_warmup': 'Opvarmning',
      'coach_suggestion_pain': 'Smerter',
      'coach_suggestion_motivation': 'Motivation',
      'coach_suggestion_pace': 'Tempo',
      'progress_title': 'Fremskridt',
      'progress_sessions': 'Løbeture',
      'progress_streak': 'Streak',
      'progress_days': 'dage',
      'progress_this_week': 'Denne uge',
      'progress_badges_title': 'Badges',
      'progress_no_badges': 'Løb din første tur for at optjene badges!',
      'badge_first_run': 'Første løbetur',
      'badge_first_run_desc': 'Du kom i gang!',
      'badge_five_runs': '5 løbeture',
      'badge_five_runs_desc': 'Konsistens er nøglen',
      'badge_ten_runs': '10 løbeture',
      'badge_ten_runs_desc': 'Du er på vej!',
      'badge_streak_3': '3 dages streak',
      'badge_streak_3_desc': 'Tre dage i træk',
      'badge_streak_7': 'Ugentlig streak',
      'badge_streak_7_desc': 'En hel uge!',
      'settings_title': 'Indstillinger',
      'settings_profile': 'Profil',
      'settings_language': 'Sprog',
      'settings_theme': 'Tema',
      'settings_theme_garmin': 'Garmin (Mørk/Teal)',
      'settings_theme_nike': 'Energi (Mørk/Rød)',
      'settings_theme_sport': 'Sport (Blå/Cyan)',
      'settings_level': 'Niveau',
      'settings_environment': 'Løbeunderlag',
      'settings_goal': 'Mål',
      'settings_reset': 'Nulstil fremskridt',
      'settings_reset_confirm': 'Er du sikker? Dette sletter alle dine data.',
      'settings_cancel': 'Annuller',
      'settings_confirm': 'Bekræft',
      'session_saved': 'Løbetur gemt!',
      'garmin_title': 'Garmin-data',
      'garmin_upload': 'Upload Garmin-skærmbillede',
      'garmin_tip': 'Tag et screenshot fra Garmin Connect og upload det her for at analysere din løbetur.',
    },
    'en': {
      'appTitle': 'RunCoach',
      'welcome_title': 'Your personal\nrunning coach',
      'welcome_subtitle': 'Built for office workers who want to run',
      'welcome_cta': 'Get Started',
      'language_title': 'Choose language',
      'language_da': 'Dansk',
      'language_en': 'English',
      'level_title': "What's your level?",
      'level_beginner': 'Beginner',
      'level_beginner_desc': 'Just starting or returning from a break',
      'level_intermediate': 'Intermediate',
      'level_intermediate_desc': 'Running regularly, want to improve',
      'level_experienced': 'Experienced',
      'level_experienced_desc': 'Running 3+ times a week with goals',
      'environment_title': 'Where do you run?',
      'environment_subtitle': 'You can change this later',
      'env_treadmill': 'Treadmill',
      'env_treadmill_desc': 'Indoors, controlled pace',
      'env_trail': 'Trail running',
      'env_trail_desc': 'Forest, hills and off-road terrain',
      'env_road': 'Road and track',
      'env_road_desc': 'Asphalt, park and running routes',
      'goal_title': "What's your goal?",
      'goal_subtitle': 'We will tailor your training plans',
      'goal_fitness': 'General fitness',
      'goal_fitness_sub': 'Stay active and healthy',
      'goal_5k': '5 kilometres',
      'goal_5k_sub': 'Complete or improve your 5K',
      'goal_10k': '10 kilometres',
      'goal_10k_sub': 'Complete or improve your 10K',
      'goal_half': 'Half marathon',
      'goal_half_sub': '21.1 km – a real challenge',
      'goal_marathon': 'Marathon',
      'goal_marathon_sub': '42.2 km – the ultimate goal',
      'nav_home': 'Home',
      'nav_training': 'Training',
      'nav_coach': 'Coach',
      'nav_progress': 'Progress',
      'nav_settings': 'Settings',
      'home_greeting_morning': 'Good morning!',
      'home_greeting_afternoon': 'Good afternoon!',
      'home_greeting_evening': 'Good evening!',
      'home_recommendation': "Today's recommendation",
      'home_streak': 'day streak',
      'home_sessions': 'sessions',
      'home_quick_start': 'Start run',
      'home_no_streak': 'Start your streak today',
      'home_tip_title': 'Coach tip',
      'training_title': 'Choose training model',
      'training_subtitle': 'Three ways to count your run',
      'model_minutes': 'Minutes',
      'model_minutes_desc': 'Interval training counted in minutes. Simple and effective.',
      'model_bpm': 'BPM',
      'model_bpm_desc': 'Find music that matches your target pace.',
      'model_lamppost': 'Lamp Posts',
      'model_lamppost_desc': 'Use street lamp posts as natural interval markers.',
      'model_premium': 'Premium',
      'bpm_title': 'Your BPM recommendation',
      'bpm_explanation': 'To reach your goal we recommend running to music at:',
      'bpm_songs_title': 'Songs at this BPM',
      'bpm_tip': 'Search these songs on Spotify or Apple Music and run to the beat.',
      'bpm_start': 'Start the run',
      'bpm_what_is': 'What is BPM?',
      'bpm_what_is_answer': 'BPM (Beats Per Minute) is the tempo of music. Running to music whose BPM matches your stride rate makes you run more rhythmically and efficiently.',
      'minutes_title': 'Interval timer',
      'minutes_round': 'Round',
      'minutes_of': 'of',
      'minutes_run': 'RUN',
      'minutes_rest': 'REST',
      'minutes_start': 'Start',
      'minutes_pause': 'Pause',
      'minutes_resume': 'Resume',
      'minutes_stop': 'Stop',
      'minutes_complete': 'Workout complete!',
      'minutes_plan': 'Training plan',
      'lamppost_title': 'Lamp post intervals',
      'lamppost_run': 'RUN to the next lamp post',
      'lamppost_rest': 'REST – walk to the next lamp post',
      'lamppost_tap': 'TAP at the lamp post',
      'lamppost_complete': 'Round complete!',
      'lamppost_total': 'Lamp posts passed',
      'lamppost_rounds': 'Rounds',
      'lamppost_stop': 'End workout',
      'coach_title': 'Your coach',
      'coach_greeting': 'Hi! I am your running coach. Ask me anything about running.',
      'coach_placeholder': 'Ask a question...',
      'coach_send': 'Send',
      'coach_suggestion_breathing': 'Breathing',
      'coach_suggestion_warmup': 'Warm-up',
      'coach_suggestion_pain': 'Pain',
      'coach_suggestion_motivation': 'Motivation',
      'coach_suggestion_pace': 'Pace',
      'progress_title': 'Progress',
      'progress_sessions': 'Sessions',
      'progress_streak': 'Streak',
      'progress_days': 'days',
      'progress_this_week': 'This week',
      'progress_badges_title': 'Badges',
      'progress_no_badges': 'Complete your first run to earn badges!',
      'badge_first_run': 'First Run',
      'badge_first_run_desc': "You're on your way!",
      'badge_five_runs': '5 Sessions',
      'badge_five_runs_desc': 'Consistency is key',
      'badge_ten_runs': '10 Sessions',
      'badge_ten_runs_desc': "You're making progress!",
      'badge_streak_3': '3-day streak',
      'badge_streak_3_desc': 'Three days in a row',
      'badge_streak_7': 'Weekly streak',
      'badge_streak_7_desc': 'A whole week!',
      'settings_title': 'Settings',
      'settings_profile': 'Profile',
      'settings_language': 'Language',
      'settings_theme': 'Theme',
      'settings_theme_garmin': 'Garmin (Dark/Teal)',
      'settings_theme_nike': 'Energy (Dark/Red)',
      'settings_theme_sport': 'Sport (Blue/Cyan)',
      'settings_level': 'Level',
      'settings_environment': 'Environment',
      'settings_goal': 'Goal',
      'settings_reset': 'Reset progress',
      'settings_reset_confirm': 'Are you sure? This deletes all your data.',
      'settings_cancel': 'Cancel',
      'settings_confirm': 'Confirm',
      'session_saved': 'Session saved!',
      'garmin_title': 'Garmin data',
      'garmin_upload': 'Upload Garmin screenshot',
      'garmin_tip': 'Take a screenshot from Garmin Connect and upload it here to analyse your run.',
    },
  };
}
